### ISSUE TITLE
Using the new builder instead of the legacy deprecated one

### ISSUE THREAD

**Issue by cursedastronaut** [ACreTeam/ac-decomp#434]
When you run `docker-setup.sh`, it prompts the following
```txt
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/
```

To help future people to be able to recompile it, it would be wise to update the builder.
Thank you

**Comment by MisterSheeple** [comment]
I've been aware of this issue for a while but haven't addressed it because for about as long as we've had the Dockerfile, we've had plans to move away from it and use Decomp Toolkit instead. But as that keeps getting postponed, it is probably a good idea to get this worked out, so I'll have a look at it soon.

**Comment by MisterSheeple** [comment]
The repo has now been switched to using DTK, making this issue obsolete.
